# Introducción a Numpy
### Crecencio J García T

## ¿Por qué numpy?

### Demo: Python 

In [10]:
%%time
num_elementos = 10000000
total = 0

for n in range(num_elementos):
    total += n

print("Total:", total)

Total: 49999995000000
CPU times: user 1.06 s, sys: 0 ns, total: 1.06 s
Wall time: 1.19 s


### Demo: Numpy

In [8]:
import numpy as np

In [11]:
%%time
elementos = np.arange(num_elementos)
total_numpy = elementos.sum()
print("Total:", total)
mismo_resultado = 'Si' if (total == total_numpy) else 'No'
print("Mismo resultado: ", mismo_resultado)

Total: 49999995000000
Mismo resultado:  Si
CPU times: user 62.5 ms, sys: 93.8 ms, total: 156 ms
Wall time: 160 ms


### Creamos una representacion de un arreglo (array)

In [15]:
xs = np.array([1, 2, 3, 4, 5, 6])

In [16]:
print(xs)

[1 2 3 4 5 6]


In [17]:
xs?

## Obteniendo la forma del arreglo (vector | matriz)


In [18]:
xs.shape

(6,)

### Creando una matriz

In [19]:
vector_a = [1, 2,  3, 4, 5]
vector_b = [6, 7, 8, 9, 10]

m = np.array([vector_a, vector_b])
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [20]:
m.shape

(2, 5)

### Crear un vector en base a un rango

In [21]:
r = np.arange(5, 100, 5)
r

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

### Crear un vector con una precision 

In [22]:
p = np.linspace(0, 5, 10)
p

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### Reformar una matriz

In [24]:
print(m)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [26]:
m.resize(5, 2)

print(m)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


### Obtener la diagonal de una matriz

In [27]:
a = [1, 2, 3]
b = [4, 5, 6]
c = [7, 8, 9]

d = np.array([a, b, c], dtype=float)
print(d)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [29]:
np.diag(d)

array([1., 5., 9.])

### Obtener una matriz nula


In [30]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Obtener una matriz identidad

In [32]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Combinar varios vectores



### Verticalmente


In [33]:
np.vstack([a, b])

array([[1, 2, 3],
       [4, 5, 6]])

### Horizontalmente

In [34]:
np.hstack([a, b])

array([1, 2, 3, 4, 5, 6])

### Transponer una matriz: Filas <=> Columnas

In [36]:
d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [37]:
d.shape

(3, 3)

In [38]:
d.T

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

### Operaciones con Vectores

In [39]:
va = np.array(a)
vb = np.array(b)
vc = np.array(c)

#### Sumar, Restar, Dividir y Multiplicar 

In [41]:
print(va, vb, vc)

[1 2 3] [4 5 6] [7 8 9]


In [43]:
print("Sumar:", (va + vb + vc))

Sumar: [12 15 18]


In [44]:
print("Restar:", (va - vb - vc))

Restar: [-10 -11 -12]


In [45]:
print("Dividir:", (va / vb))

Dividir: [0.25 0.4  0.5 ]


In [46]:
print("Multiplicar:", (va * vb))

Multiplicar: [ 4 10 18]


In [49]:
print("Potenciación (2 como base y el vector como potencia):", (2 ** va))

Potenciación (2 como base y el vector como potencia): [2 4 8]


In [50]:
print("Potencia de 2 de un vector:", (va**2))

Potencia de 2 de un vector: [1 4 9]


#### Producto escalar:  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [51]:
va.dot(vb)

32

## Funciones Matematicas de Agregacición:


In [55]:
vs = np.hstack([va, vb, vc])
vs

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
vs.sum()


45

In [58]:
vs.max()

9

In [59]:
vs.min()

1

In [60]:
vs.std()

2.581988897471611

In [62]:
vs.mean()

5.0

### Obteniendo el index del arg con menor o mayor valor:

In [63]:
vs.argmax()

8

In [64]:
vs.argmin()

0

## Cambiar el tipo de datos de un vector

In [66]:
vs.dtype

dtype('int64')

In [67]:
vs = vs.astype('f')
vs.dtype

dtype('float32')

## Vector Slicing:

In [69]:
print(vs[:5])

[1. 2. 3. 4. 5.]


In [73]:
print(vs)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [74]:
print(vs[3:8])

[4. 5. 6. 7. 8.]


#### Establecer el incremento en el slicing de un vector: \[inicio:final:incremento\]

In [75]:
print(vs[::3])

[1. 4. 7.]


In [76]:
print(vs[::2])

[1. 3. 5. 7. 9.]


In [77]:
print(vs[1::2])

[2. 4. 6. 8.]


## Obtener un número (escalar) aleatorio:

In [94]:
r = np.random.randint(9)
print(r)

7


### Obtener un número aleatorio entre min y max:

In [106]:
r = np.random.randint(0, 100)
print(r)

83


### Obtener un vector con valores aleatorios:

In [124]:
r = np.random.randint(0, 100, size=(9))
print(r)

[[59 90]
 [49 35]]


## Matriz Slicing 

In [125]:
print(d)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### Obtener el valor \(2,2\) = \{fila, columna\}

In [128]:
print(d[2,2])

9.0


### ¿Como encontramos el valor de la 2da fila, en la 3ra columna?

In [130]:
print(d[1,2])

6.0


## Filtros en matrices

### Encontremos todos los valores mayores que 2

In [131]:
print(d)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [132]:
resultado = d[ d > 2]
print(resultado)


[3. 4. 5. 6. 7. 8. 9.]


### Sustituir los valores que cumplan una condición

In [133]:
m3 = d.copy()
print(m3)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [135]:
m3[m3 % 3 == 0] = 3
print(m3)

[[1. 2. 3.]
 [4. 5. 3.]
 [7. 8. 3.]]
